
CREATE TABLE ANSWER_LIST
(
  ANSWER_UID VARCHAR(200) NOT NULL COMMENT '답항 대표값',
  ANSWER     VARCHAR(200) NULL     COMMENT '답항 내용',
  ORDERS     INTEGER      NULL     COMMENT '번호',
  PRIMARY KEY (ANSWER_UID)
) COMMENT '답항 리스트';

CREATE TABLE QA_DATA
(
  QUESTION_UID VARCHAR(200) NOT NULL COMMENT '문항 대표값',
  ANSWER_UID   VARCHAR(200) NOT NULL COMMENT '답항 대표값'
) COMMENT '문항 답항 데이터';

CREATE TABLE QUESTION_LIST
(
  QUESTION_UID VARCHAR(200) NOT NULL COMMENT '문항 대표값',
  QUESTION     VARCHAR(200) NULL     COMMENT '문항 내용',
  ORDERS       INTEGER      NULL     COMMENT '번호',
  PRIMARY KEY (QUESTION_UID)
) COMMENT '문항 리스트';

CREATE TABLE SURVEY_DATA
(
  QUESTION_UID VARCHAR(200) NOT NULL COMMENT '문항 대표값',
  ANSWER_UID   VARCHAR(200) NOT NULL COMMENT '답항 대표값',
  USER_UID     VARCHAR(200) NOT NULL COMMENT '유저 대표값'
) COMMENT '설문 데이터';

CREATE TABLE USERDATA
(
  USER_UID     VARCHAR(200) NOT NULL COMMENT '유저 대표값',
  NAME         VARCHAR(200) NULL     COMMENT '이름',
  ID           VARCHAR(200) NULL     COMMENT '아이디',
  PASSWORD     VARCHAR(200) NULL     COMMENT '비밀번호',
  PHONE_NUMBER VARCHAR(200) NULL     COMMENT '전화번호',
  BIRTHDAY     VARCHAR(200) NULL     COMMENT '생년월일',
  EMAIL        VARCHAR(200) NULL     COMMENT '이메일주소',
  SMS_AD       BOOLEAN      NULL     COMMENT '에스엠에스수신여부',
  EMAIL_AD     BOOLEAN      NULL     COMMENT '이메일수신여부',
  PRIMARY KEY (USER_UID)
) COMMENT '유저 데이터';

ALTER TABLE QA_DATA
  ADD CONSTRAINT FK_QUESTION_LIST_TO_QA_DATA
    FOREIGN KEY (QUESTION_UID)
    REFERENCES QUESTION_LIST (QUESTION_UID);

ALTER TABLE QA_DATA
  ADD CONSTRAINT FK_ANSWER_LIST_TO_QA_DATA
    FOREIGN KEY (ANSWER_UID)
    REFERENCES ANSWER_LIST (ANSWER_UID);

ALTER TABLE SURVEY_DATA
  ADD CONSTRAINT FK_QUESTION_LIST_TO_SURVEY_DATA
    FOREIGN KEY (QUESTION_UID)
    REFERENCES QUESTION_LIST (QUESTION_UID);

ALTER TABLE SURVEY_DATA
  ADD CONSTRAINT FK_ANSWER_LIST_TO_SURVEY_DATA
    FOREIGN KEY (ANSWER_UID)
    REFERENCES ANSWER_LIST (ANSWER_UID);

ALTER TABLE SURVEY_DATA
  ADD CONSTRAINT FK_USERDATA_TO_SURVEY_DATA
    FOREIGN KEY (USER_UID)
    REFERENCES USERDATA (USER_UID);
